//
//  Enum.h
//  FileThis
//
//  Created by Manh Nguyen Ngoc on 12/03/13.
//  Copyright (c) 2013 PlanvSoftware. All rights reserved.
//

typedef enum
{
    EVENT_TYPE_LOAD_COMMON_DATA,
    EVENT_TYPE_LOAD_DOCUMENTS_IN_CAB_DATA,
    EVENT_TYPE_LOAD_DOCUMENTS_IN_PROFILE_DATA,
    EVENT_TYPE_LOAD_DOCUMENT_THUMBNAIL,
    EVENT_TYPE_ADD_TAGS_TO_DOCUMENTS,
    EVENT_TYPE_REMOVE_TAGS_FROM_DOCUMENTS,
    EVENT_TYPE_ADD_CABS_TO_DOCUMENTS,
    EVENT_TYPE_REMOVE_CABS_FROM_DOCUMENTS,
    EVENT_TYPE_DELETE_DOC,
    EVENT_TYPE_DELETE_DOCS,
    EVENT_TYPE_EDIT_DOC,
    EVENT_TYPE_ADD_CABINET,
    EVENT_TYPE_ADD_TAG,
    EVENT_TYPE_LOAD_ALL_DATA,
    EVENT_TYPE_REMOVE_TAG,
    EVENT_TYPE_REMOVE_CABINET,
    EVENT_TYPE_CANCEL_LOADING_DATA,
    EVENT_TYPE_FINISHED_DISPLAYING_DOCUMENT_LIST
} EVENTTYPE;

typedef enum
{
    STATUS_OK,
	STATUS_WARNING,
	STATUS_ERROR
} EVENTSTATUS;

typedef enum
{
    CHANNEL_UI,
    CHANNEL_DATA
} CHANNEL_PIPE;
